const mockProducts = [
    // ─── LIVING ROOM > SOFAS ───────────────────────────────
    {
        _id: 'VG-101',
        name: 'Natuzzi Leather L-Shape Sofa',
        slug: 'natuzzi-leather-l-shape-sofa',
        brand: 'Natuzzi',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'L-Shaped Sofas',
        finish: 'Genuine Leather',
        images: [{ url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-101-DEFAULT', price: 212500, compare_price: 250000, inventory_quantity: 12, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-121',
        name: 'Ashley Modern Sectional Sofa',
        slug: 'ashley-modern-sectional-sofa',
        brand: 'Ashley',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'L-Shaped Sofas',
        finish: 'Linen',
        images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-121-DEFAULT', price: 69149, compare_price: 81352, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-122',
        name: 'FabIndia Modern 3-Seater Sofa',
        slug: 'fabindia-modern-3-seater-sofa',
        brand: 'FabIndia',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: '3-Seater Sofas',
        finish: 'Genuine Leather',
        images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-122-DEFAULT', price: 150553, compare_price: 215076, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-123',
        name: 'IKEA Premium Chesterfield Sofa',
        slug: 'ikea-premium-chesterfield-sofa',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Chesterfield Sofas',
        finish: 'Premium Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-123-DEFAULT', price: 109328, compare_price: 109328, inventory_quantity: 100, inventory_reserved: 0 }],
    },
    // Fabric Sofas
    {
        _id: 'VG-201',
        name: 'Urban Ladder Fabric 3-Seater Sofa',
        slug: 'urban-ladder-fabric-3-seater-sofa',
        brand: 'Urban Ladder',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Fabric Sofas',
        finish: 'Premium Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-201-DEFAULT', price: 42000, compare_price: 52000, inventory_quantity: 15, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-202',
        name: 'Pepperfry Velvet Fabric Sofa',
        slug: 'pepperfry-velvet-fabric-sofa',
        brand: 'Pepperfry',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Fabric Sofas',
        finish: 'Velvet Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-202-DEFAULT', price: 38500, compare_price: 45000, inventory_quantity: 20, inventory_reserved: 0 }],
    },
    // Wooden Sofas
    {
        _id: 'VG-203',
        name: 'Wooden Street Sheesham Wood Sofa',
        slug: 'wooden-street-sheesham-wood-sofa',
        brand: 'Wooden Street',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Wooden Sofas',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-203-DEFAULT', price: 55000, compare_price: 68000, inventory_quantity: 8, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-204',
        name: 'Durian Teak Wood Sofa Set',
        slug: 'durian-teak-wood-sofa-set',
        brand: 'Durian',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Wooden Sofas',
        finish: 'Teak Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-204-DEFAULT', price: 72000, compare_price: 88000, inventory_quantity: 6, inventory_reserved: 0 }],
    },
    // Sofa Cum Beds
    {
        _id: 'VG-114',
        name: 'Urban Ladder Sofa Cum Bed',
        slug: 'urban-ladder-sofa-cum-bed',
        brand: 'Urban Ladder',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Sofa Cum Beds',
        finish: 'Premium Fabric & Foam',
        images: [{ url: 'https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-114-DEFAULT', price: 34200, compare_price: 38000, inventory_quantity: 10, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-205',
        name: 'Nilkamal Foldable Sofa Cum Bed',
        slug: 'nilkamal-foldable-sofa-cum-bed',
        brand: 'Nilkamal',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Sofa Cum Beds',
        finish: 'Microfiber Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-205-DEFAULT', price: 28000, compare_price: 33000, inventory_quantity: 14, inventory_reserved: 0 }],
    },
    // Recliners
    {
        _id: 'VG-103',
        name: 'Stanley Motorized Recliner',
        slug: 'stanley-motorized-recliner',
        brand: 'Stanley',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Recliners',
        finish: 'Top Grain Leather',
        images: [{ url: 'https://images.unsplash.com/photo-1583847268964-b28e5f8f8101?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-103-DEFAULT', price: 80750, compare_price: 85000, inventory_quantity: 3, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-206',
        name: 'Durian Power Recliner Sofa',
        slug: 'durian-power-recliner-sofa',
        brand: 'Durian',
        category: 'Living Room',
        subcategory: 'Sofas',
        item_type: 'Recliners',
        finish: 'Half Leather',
        images: [{ url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-206-DEFAULT', price: 65000, compare_price: 78000, inventory_quantity: 5, inventory_reserved: 0 }],
    },

    // ─── LIVING ROOM > SEATING ─────────────────────────────
    {
        _id: 'VG-109',
        name: 'Roche Bobois Lounge Chair',
        slug: 'roche-bobois-lounge-chair',
        brand: 'Roche Bobois',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Lounge Chairs',
        finish: 'Premium Fabric & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-109-DEFAULT', price: 150000, compare_price: 150000, inventory_quantity: 2, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-207',
        name: 'Urban Ladder Oslo Lounge Chair',
        slug: 'urban-ladder-oslo-lounge-chair',
        brand: 'Urban Ladder',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Lounge Chairs',
        finish: 'Leatherette & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-207-DEFAULT', price: 32000, compare_price: 40000, inventory_quantity: 9, inventory_reserved: 0 }],
    },
    // Accent Chairs
    {
        _id: 'VG-208',
        name: 'Pepperfry Velvet Accent Chair',
        slug: 'pepperfry-velvet-accent-chair',
        brand: 'Pepperfry',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Accent Chairs',
        finish: 'Velvet & Wooden Legs',
        images: [{ url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-208-DEFAULT', price: 18500, compare_price: 24000, inventory_quantity: 22, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-209',
        name: 'FabIndia Handwoven Accent Chair',
        slug: 'fabindia-handwoven-accent-chair',
        brand: 'FabIndia',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Accent Chairs',
        finish: 'Cotton Fabric & Teak',
        images: [{ url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-209-DEFAULT', price: 22000, compare_price: 27000, inventory_quantity: 16, inventory_reserved: 0 }],
    },
    // Wing Chairs
    {
        _id: 'VG-129',
        name: 'Roche Bobois Linen Wingback Chair',
        slug: 'roche-bobois-linen-wingback-chair',
        brand: 'Roche Bobois',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Wing Chairs',
        finish: 'Linen & Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-129-DEFAULT', price: 77413, compare_price: 110591, inventory_quantity: 50, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-210',
        name: 'Stanley Classic Wing Chair',
        slug: 'stanley-classic-wing-chair',
        brand: 'Stanley',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Wing Chairs',
        finish: 'Chenille Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-210-DEFAULT', price: 45000, compare_price: 56000, inventory_quantity: 7, inventory_reserved: 0 }],
    },
    // Benches
    {
        _id: 'VG-211',
        name: 'Wooden Street Sheesham Bench',
        slug: 'wooden-street-sheesham-bench',
        brand: 'Wooden Street',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Benches',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-211-DEFAULT', price: 14000, compare_price: 18000, inventory_quantity: 30, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-212',
        name: 'IKEA Upholstered Storage Bench',
        slug: 'ikea-upholstered-storage-bench',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Benches',
        finish: 'Fabric & MDF',
        images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-212-DEFAULT', price: 9500, compare_price: 12000, inventory_quantity: 40, inventory_reserved: 0 }],
    },
    // Pouffes
    {
        _id: 'VG-213',
        name: 'H&M Home Round Knitted Pouffe',
        slug: 'hm-home-round-knitted-pouffe',
        brand: 'H&M Home',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Pouffes',
        finish: 'Knitted Cotton',
        images: [{ url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-213-DEFAULT', price: 4500, compare_price: 6000, inventory_quantity: 55, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-214',
        name: 'Nestasia Leather Ottoman Pouffe',
        slug: 'nestasia-leather-ottoman-pouffe',
        brand: 'Nestasia',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Pouffes',
        finish: 'PU Leather',
        images: [{ url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-214-DEFAULT', price: 6800, compare_price: 8500, inventory_quantity: 38, inventory_reserved: 0 }],
    },
    // Rocking Chairs
    {
        _id: 'VG-128',
        name: 'Roche Bobois Wicker Rocking Chair',
        slug: 'roche-bobois-wicker-rocking-chair',
        brand: 'Roche Bobois',
        category: 'Living Room',
        subcategory: 'Seating',
        item_type: 'Rocking Chairs',
        finish: 'Wicker',
        images: [{ url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-128-DEFAULT', price: 134160, compare_price: 167701, inventory_quantity: 60, inventory_reserved: 0 }],
    },

    // ─── LIVING ROOM > TABLES ──────────────────────────────
    {
        _id: 'VG-102',
        name: 'BoConcept Modern Coffee Table',
        slug: 'boconcept-modern-coffee-table',
        brand: 'BoConcept',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Coffee Tables',
        finish: 'Engineered Wood & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-102-DEFAULT', price: 40500, compare_price: 45000, inventory_quantity: 25, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-215',
        name: 'Wooden Street Mango Wood Coffee Table',
        slug: 'wooden-street-mango-wood-coffee-table',
        brand: 'Wooden Street',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Coffee Tables',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-215-DEFAULT', price: 18000, compare_price: 22000, inventory_quantity: 18, inventory_reserved: 0 }],
    },
    // Side Tables
    {
        _id: 'VG-216',
        name: 'West Elm Marble Side Table',
        slug: 'west-elm-marble-side-table',
        brand: 'West Elm',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Side Tables',
        finish: 'Marble & Gold Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-216-DEFAULT', price: 16500, compare_price: 20000, inventory_quantity: 24, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-217',
        name: 'IKEA Bamboo Side Table',
        slug: 'ikea-bamboo-side-table',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Side Tables',
        finish: 'Bamboo',
        images: [{ url: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-217-DEFAULT', price: 4500, compare_price: 5500, inventory_quantity: 60, inventory_reserved: 0 }],
    },
    // Console Tables
    {
        _id: 'VG-125',
        name: 'IKEA Minimalist Console Table',
        slug: 'ikea-minimalist-console-table',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Console Tables',
        finish: 'Marble & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-125-DEFAULT', price: 14658, compare_price: 14658, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-218',
        name: 'Pottery Barn Slim Console Table',
        slug: 'pottery-barn-slim-console-table',
        brand: 'Pottery Barn',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Console Tables',
        finish: 'Solid Acacia Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-218-DEFAULT', price: 28000, compare_price: 34000, inventory_quantity: 12, inventory_reserved: 0 }],
    },
    // End Tables
    {
        _id: 'VG-219',
        name: 'West Elm Round End Table',
        slug: 'west-elm-round-end-table',
        brand: 'West Elm',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'End Tables',
        finish: 'Walnut Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-219-DEFAULT', price: 12000, compare_price: 15000, inventory_quantity: 28, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-220',
        name: 'Pepperfry Metal End Table',
        slug: 'pepperfry-metal-end-table',
        brand: 'Pepperfry',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'End Tables',
        finish: 'Metal & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-220-DEFAULT', price: 8500, compare_price: 11000, inventory_quantity: 35, inventory_reserved: 0 }],
    },
    // Nesting Tables
    {
        _id: 'VG-126',
        name: 'West Elm Designer Nesting Tables',
        slug: 'west-elm-designer-nesting-tables',
        brand: 'West Elm',
        category: 'Living Room',
        subcategory: 'Tables',
        item_type: 'Nesting Tables',
        finish: 'Engineered Wood & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1499933374294-4584851497cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-126-DEFAULT', price: 7617, compare_price: 8464, inventory_quantity: 86, inventory_reserved: 0 }],
    },

    // ─── LIVING ROOM > STORAGE ─────────────────────────────
    {
        _id: 'VG-111',
        name: 'Ashley Furniture TV Unit',
        slug: 'ashley-furniture-tv-unit',
        brand: 'Ashley',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'TV Units',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-111-DEFAULT', price: 35700, compare_price: 42000, inventory_quantity: 18, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-221',
        name: 'Wooden Street Sheesham TV Unit',
        slug: 'wooden-street-sheesham-tv-unit',
        brand: 'Wooden Street',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'TV Units',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-221-DEFAULT', price: 28000, compare_price: 35000, inventory_quantity: 22, inventory_reserved: 0 }],
    },
    // Bookshelves
    {
        _id: 'VG-110',
        name: 'FabIndia Handcarved Bookshelf',
        slug: 'fabindia-handcarved-bookshelf',
        brand: 'FabIndia',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Bookshelves',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-110-DEFAULT', price: 28000, compare_price: 35000, inventory_quantity: 15, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-222',
        name: 'IKEA Billy Bookcase',
        slug: 'ikea-billy-bookcase',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Bookshelves',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-222-DEFAULT', price: 8500, compare_price: 10000, inventory_quantity: 45, inventory_reserved: 0 }],
    },
    // Display Units
    {
        _id: 'VG-132',
        name: 'IKEA Modern Display Unit',
        slug: 'ikea-modern-display-unit',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Display Units',
        finish: 'Solid Teak Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-132-DEFAULT', price: 42098, compare_price: 60140, inventory_quantity: 65, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-223',
        name: 'Pottery Barn Glass Display Cabinet',
        slug: 'pottery-barn-glass-display-cabinet',
        brand: 'Pottery Barn',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Display Units',
        finish: 'Oak & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-223-DEFAULT', price: 52000, compare_price: 65000, inventory_quantity: 10, inventory_reserved: 0 }],
    },
    // Shoe Racks
    {
        _id: 'VG-113',
        name: 'IKEA Hemnes Shoe Cabinet',
        slug: 'ikea-hemnes-shoe-cabinet',
        brand: 'IKEA',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Shoe Racks',
        finish: 'Solid Pine Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-113-DEFAULT', price: 11400, compare_price: 12000, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-224',
        name: 'Nilkamal Plastic Shoe Rack',
        slug: 'nilkamal-plastic-shoe-rack',
        brand: 'Nilkamal',
        category: 'Living Room',
        subcategory: 'Storage',
        item_type: 'Shoe Racks',
        finish: 'Plastic',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-224-DEFAULT', price: 3200, compare_price: 4000, inventory_quantity: 80, inventory_reserved: 0 }],
    },

    // ─── BEDROOM > BEDS ────────────────────────────────────
    {
        _id: 'VG-104',
        name: 'Durian Solid Wood King Bed',
        slug: 'durian-solid-wood-king-bed',
        brand: 'Durian',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'King Size Beds',
        finish: 'Solid Teak Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-104-DEFAULT', price: 60000, compare_price: 75000, inventory_quantity: 8, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-225',
        name: 'Wooden Street Teak King Size Bed',
        slug: 'wooden-street-teak-king-size-bed',
        brand: 'Wooden Street',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'King Size Beds',
        finish: 'Teak Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-225-DEFAULT', price: 52000, compare_price: 63000, inventory_quantity: 10, inventory_reserved: 0 }],
    },
    // Queen Size Beds
    {
        _id: 'VG-120',
        name: 'Ethan Allen Queen Size Bed',
        slug: 'ethan-allen-queen-size-bed',
        brand: 'Ethan Allen',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Queen Size Beds',
        finish: 'Solid Wood & Velvet',
        images: [{ url: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-120-DEFAULT', price: 88000, compare_price: 110000, inventory_quantity: 2, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-226',
        name: 'Godrej Interio Queen Bed with Storage',
        slug: 'godrej-interio-queen-bed-storage',
        brand: 'Godrej Interio',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Queen Size Beds',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-226-DEFAULT', price: 42000, compare_price: 52000, inventory_quantity: 14, inventory_reserved: 0 }],
    },
    // Solid Wood Beds
    {
        _id: 'VG-227',
        name: 'Durian Sheesham Solid Wood Bed',
        slug: 'durian-sheesham-solid-wood-bed',
        brand: 'Durian',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Solid Wood Beds',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-227-DEFAULT', price: 48000, compare_price: 60000, inventory_quantity: 9, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-228',
        name: 'Wooden Street Acacia Solid Wood Bed',
        slug: 'wooden-street-acacia-solid-wood-bed',
        brand: 'Wooden Street',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Solid Wood Beds',
        finish: 'Acacia Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-228-DEFAULT', price: 38000, compare_price: 46000, inventory_quantity: 12, inventory_reserved: 0 }],
    },
    // Upholstered Beds
    {
        _id: 'VG-134',
        name: 'IKEA Solid Upholstered Bed',
        slug: 'ikea-solid-upholstered-bed',
        brand: 'IKEA',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Upholstered Beds',
        finish: 'Solid Wood & Velvet',
        images: [{ url: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-134-DEFAULT', price: 43061, compare_price: 61517, inventory_quantity: 40, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-229',
        name: 'Pottery Barn Velvet Upholstered Bed',
        slug: 'pottery-barn-velvet-upholstered-bed',
        brand: 'Pottery Barn',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Upholstered Beds',
        finish: 'Velvet & Pine Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-229-DEFAULT', price: 68000, compare_price: 82000, inventory_quantity: 6, inventory_reserved: 0 }],
    },
    // Beds with Storage
    {
        _id: 'VG-230',
        name: 'Godrej Interio Hydraulic Storage Bed',
        slug: 'godrej-interio-hydraulic-storage-bed',
        brand: 'Godrej Interio',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Beds with Storage',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-230-DEFAULT', price: 38000, compare_price: 46000, inventory_quantity: 18, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-231',
        name: 'Durian Box Storage Bed',
        slug: 'durian-box-storage-bed',
        brand: 'Durian',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Beds with Storage',
        finish: 'Laminated Board',
        images: [{ url: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-231-DEFAULT', price: 32000, compare_price: 40000, inventory_quantity: 22, inventory_reserved: 0 }],
    },
    // Bunk Beds
    {
        _id: 'VG-133',
        name: 'Godrej Interio Luxury Bunk Bed',
        slug: 'godrej-interio-luxury-bunk-bed',
        brand: 'Godrej Interio',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Bunk Beds',
        finish: 'Metal Frame',
        images: [{ url: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-133-DEFAULT', price: 54219, compare_price: 54219, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-232',
        name: 'IKEA Wooden Bunk Bed',
        slug: 'ikea-wooden-bunk-bed',
        brand: 'IKEA',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Bunk Beds',
        finish: 'Pine Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-232-DEFAULT', price: 28000, compare_price: 35000, inventory_quantity: 15, inventory_reserved: 0 }],
    },
    // Canopy Beds
    {
        _id: 'VG-135',
        name: 'Godrej Interio Solid Canopy Bed',
        slug: 'godrej-interio-solid-canopy-bed',
        brand: 'Godrej Interio',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Canopy Beds',
        finish: 'Solid Wood & Velvet',
        images: [{ url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-135-DEFAULT', price: 148107, compare_price: 148107, inventory_quantity: 38, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-233',
        name: 'Pottery Barn Four-Poster Canopy Bed',
        slug: 'pottery-barn-four-poster-canopy-bed',
        brand: 'Pottery Barn',
        category: 'Bedroom',
        subcategory: 'Beds',
        item_type: 'Canopy Beds',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1560067174-c5a3a8f37060?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-233-DEFAULT', price: 95000, compare_price: 120000, inventory_quantity: 4, inventory_reserved: 0 }],
    },

    // ─── BEDROOM > STORAGE ─────────────────────────────────
    {
        _id: 'VG-108',
        name: 'Pottery Barn Mirrored Wardrobe',
        slug: 'pottery-barn-mirrored-wardrobe',
        brand: 'Pottery Barn',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Wardrobes',
        finish: 'Engineered Wood & Mirror',
        images: [{ url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-108-DEFAULT', price: 85500, compare_price: 95000, inventory_quantity: 6, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-234',
        name: 'Godrej Interio 3-Door Wardrobe',
        slug: 'godrej-interio-3-door-wardrobe',
        brand: 'Godrej Interio',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Wardrobes',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-234-DEFAULT', price: 48000, compare_price: 58000, inventory_quantity: 14, inventory_reserved: 0 }],
    },
    // Chest of Drawers
    {
        _id: 'VG-235',
        name: 'IKEA Hemnes Chest of Drawers',
        slug: 'ikea-hemnes-chest-of-drawers',
        brand: 'IKEA',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Chest of Drawers',
        finish: 'Pine Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-235-DEFAULT', price: 22000, compare_price: 28000, inventory_quantity: 20, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-236',
        name: 'Wooden Street Sheesham Chest of Drawers',
        slug: 'wooden-street-sheesham-chest-drawers',
        brand: 'Wooden Street',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Chest of Drawers',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-236-DEFAULT', price: 32000, compare_price: 40000, inventory_quantity: 12, inventory_reserved: 0 }],
    },
    // Bedside Tables
    {
        _id: 'VG-136',
        name: 'Durian Laminated Nightstand',
        slug: 'durian-laminated-nightstand',
        brand: 'Durian',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Bedside Tables',
        finish: 'Laminated Board',
        images: [{ url: 'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-136-DEFAULT', price: 41481, compare_price: 55309, inventory_quantity: 4, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-237',
        name: 'IKEA Tarva Bedside Table',
        slug: 'ikea-tarva-bedside-table',
        brand: 'IKEA',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Bedside Tables',
        finish: 'Solid Pine',
        images: [{ url: 'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-237-DEFAULT', price: 6500, compare_price: 8000, inventory_quantity: 50, inventory_reserved: 0 }],
    },
    // Dressers
    {
        _id: 'VG-138',
        name: 'Wipro Premium Dresser',
        slug: 'wipro-premium-dresser',
        brand: 'Wipro',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Dressers',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-138-DEFAULT', price: 54702, compare_price: 78146, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-238',
        name: 'Wooden Street Teak Dresser with Mirror',
        slug: 'wooden-street-teak-dresser-mirror',
        brand: 'Wooden Street',
        category: 'Bedroom',
        subcategory: 'Storage',
        item_type: 'Dressers',
        finish: 'Teak Wood & Mirror',
        images: [{ url: 'https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-238-DEFAULT', price: 38000, compare_price: 48000, inventory_quantity: 8, inventory_reserved: 0 }],
    },

    // ─── BEDROOM > MATTRESSES ──────────────────────────────
    {
        _id: 'VG-112',
        name: 'Duroflex Memory Foam Mattress',
        slug: 'duroflex-memory-foam-mattress',
        brand: 'Duroflex',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Memory Foam',
        finish: 'Memory Foam & Cotton',
        images: [{ url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-112-DEFAULT', price: 21000, compare_price: 28000, inventory_quantity: 50, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-239',
        name: 'Sleepwell Memory Foam Pro Mattress',
        slug: 'sleepwell-memory-foam-pro-mattress',
        brand: 'Sleepwell',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Memory Foam',
        finish: 'Memory Foam & Knit Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-239-DEFAULT', price: 18500, compare_price: 24000, inventory_quantity: 35, inventory_reserved: 0 }],
    },
    // Orthopedic
    {
        _id: 'VG-105',
        name: 'Sleepwell Ortho Pro Mattress',
        slug: 'sleepwell-ortho-pro-mattress',
        brand: 'Sleepwell',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Orthopedic',
        finish: 'High-Resilience Foam',
        images: [{ url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-105-DEFAULT', price: 19800, compare_price: 22000, inventory_quantity: 40, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-240',
        name: 'Duroflex Ortholife Mattress',
        slug: 'duroflex-ortholife-mattress',
        brand: 'Duroflex',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Orthopedic',
        finish: 'Bonnell Spring & Foam',
        images: [{ url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-240-DEFAULT', price: 15500, compare_price: 20000, inventory_quantity: 45, inventory_reserved: 0 }],
    },
    // Dual Comfort
    {
        _id: 'VG-241',
        name: 'Centuary Dual Comfort Mattress',
        slug: 'centuary-dual-comfort-mattress',
        brand: 'Centuary',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Dual Comfort',
        finish: 'Foam & Coir',
        images: [{ url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-241-DEFAULT', price: 12000, compare_price: 15000, inventory_quantity: 60, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-242',
        name: 'Sleepwell Dual Comfort Reversible Mattress',
        slug: 'sleepwell-dual-comfort-reversible',
        brand: 'Sleepwell',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Dual Comfort',
        finish: 'Soft & Firm Foam',
        images: [{ url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-242-DEFAULT', price: 14000, compare_price: 18000, inventory_quantity: 42, inventory_reserved: 0 }],
    },
    // Coir Mattresses
    {
        _id: 'VG-243',
        name: 'Duroflex Coir Mattress',
        slug: 'duroflex-coir-mattress',
        brand: 'Duroflex',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Coir Mattresses',
        finish: 'Natural Coir',
        images: [{ url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-243-DEFAULT', price: 8500, compare_price: 11000, inventory_quantity: 55, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-244',
        name: 'Centuary Rubberized Coir Mattress',
        slug: 'centuary-rubberized-coir-mattress',
        brand: 'Centuary',
        category: 'Bedroom',
        subcategory: 'Mattresses',
        item_type: 'Coir Mattresses',
        finish: 'Rubberized Coir',
        images: [{ url: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-244-DEFAULT', price: 10000, compare_price: 13000, inventory_quantity: 48, inventory_reserved: 0 }],
    },

    // ─── DINING > DINING SETS ──────────────────────────────
    {
        _id: 'VG-106',
        name: 'West Elm 6-Seater Dining Set',
        slug: 'west-elm-6-seater-dining-set',
        brand: 'West Elm',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '6 Seater Dining Sets',
        finish: 'Solid Oak Wood & Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1617806118233-18e1c0945594?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-106-DEFAULT', price: 102000, compare_price: 120000, inventory_quantity: 5, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-245',
        name: 'Wooden Street 6-Seater Dining Set',
        slug: 'wooden-street-6-seater-dining-set',
        brand: 'Wooden Street',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '6 Seater Dining Sets',
        finish: 'Sheesham Wood & Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-245-DEFAULT', price: 72000, compare_price: 90000, inventory_quantity: 8, inventory_reserved: 0 }],
    },
    // 4 Seater
    {
        _id: 'VG-246',
        name: 'IKEA 4-Seater Dining Table Set',
        slug: 'ikea-4-seater-dining-table-set',
        brand: 'IKEA',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '4 Seater Dining Sets',
        finish: 'Birch Wood & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-246-DEFAULT', price: 28000, compare_price: 35000, inventory_quantity: 20, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-247',
        name: 'Pepperfry 4-Seater Solid Wood Dining Set',
        slug: 'pepperfry-4-seater-solid-wood-dining-set',
        brand: 'Pepperfry',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '4 Seater Dining Sets',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1617806118233-18e1c0945594?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-247-DEFAULT', price: 22000, compare_price: 28000, inventory_quantity: 25, inventory_reserved: 0 }],
    },
    // 8 Seater
    {
        _id: 'VG-144',
        name: 'Nilkamal Modern 8 Seater Dining Set',
        slug: 'nilkamal-modern-8-seater-dining-set',
        brand: 'Nilkamal',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '8 Seater Dining Sets',
        finish: 'Mango Wood & Cotton',
        images: [{ url: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-144-DEFAULT', price: 109431, compare_price: 145909, inventory_quantity: 70, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-248',
        name: 'Wooden Street 8-Seater Teak Dining Set',
        slug: 'wooden-street-8-seater-teak-dining-set',
        brand: 'Wooden Street',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: '8 Seater Dining Sets',
        finish: 'Teak Wood & Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-248-DEFAULT', price: 135000, compare_price: 165000, inventory_quantity: 5, inventory_reserved: 0 }],
    },
    // Extendable Dining
    {
        _id: 'VG-142',
        name: 'Wooden Street Extendable Dining Set',
        slug: 'wooden-street-extendable-dining-set',
        brand: 'Wooden Street',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: 'Extendable Dining',
        finish: 'Teak Wood & Jute',
        images: [{ url: 'https://images.unsplash.com/photo-1617806118233-18e1c0945594?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-142-DEFAULT', price: 121546, compare_price: 173638, inventory_quantity: 43, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-249',
        name: 'IKEA Vangsta Extendable Dining Table',
        slug: 'ikea-vangsta-extendable-dining-table',
        brand: 'IKEA',
        category: 'Dining',
        subcategory: 'Dining Sets',
        item_type: 'Extendable Dining',
        finish: 'White Lacquer',
        images: [{ url: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-249-DEFAULT', price: 18000, compare_price: 22000, inventory_quantity: 30, inventory_reserved: 0 }],
    },

    // ─── DINING > DINING STORAGE ───────────────────────────
    // Crockery Units
    {
        _id: 'VG-250',
        name: 'Wooden Street Sheesham Crockery Unit',
        slug: 'wooden-street-sheesham-crockery-unit',
        brand: 'Wooden Street',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Crockery Units',
        finish: 'Sheesham Wood & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-250-DEFAULT', price: 38000, compare_price: 48000, inventory_quantity: 12, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-251',
        name: 'Pepperfry Glass Crockery Cabinet',
        slug: 'pepperfry-glass-crockery-cabinet',
        brand: 'Pepperfry',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Crockery Units',
        finish: 'Engineered Wood & Glass',
        images: [{ url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-251-DEFAULT', price: 24000, compare_price: 30000, inventory_quantity: 18, inventory_reserved: 0 }],
    },
    // Kitchen Cabinets
    {
        _id: 'VG-252',
        name: 'Godrej Interio Modular Kitchen Cabinet',
        slug: 'godrej-interio-modular-kitchen-cabinet',
        brand: 'Godrej Interio',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Kitchen Cabinets',
        finish: 'Laminated MDF',
        images: [{ url: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-252-DEFAULT', price: 45000, compare_price: 58000, inventory_quantity: 10, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-253',
        name: 'IKEA Metod Kitchen Cabinet',
        slug: 'ikea-metod-kitchen-cabinet',
        brand: 'IKEA',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Kitchen Cabinets',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-253-DEFAULT', price: 22000, compare_price: 28000, inventory_quantity: 25, inventory_reserved: 0 }],
    },
    // Sideboards
    {
        _id: 'VG-115',
        name: 'Pepperfry Wooden Sideboard',
        slug: 'pepperfry-wooden-sideboard',
        brand: 'Pepperfry',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Sideboards',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-115-DEFAULT', price: 22100, compare_price: 26000, inventory_quantity: 14, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-254',
        name: 'West Elm Mid-Century Sideboard',
        slug: 'west-elm-mid-century-sideboard',
        brand: 'West Elm',
        category: 'Dining',
        subcategory: 'Dining Storage',
        item_type: 'Sideboards',
        finish: 'Walnut Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-254-DEFAULT', price: 55000, compare_price: 68000, inventory_quantity: 7, inventory_reserved: 0 }],
    },

    // ─── DINING > DINING DECOR ─────────────────────────────
    // Table Linens
    {
        _id: 'VG-255',
        name: 'H&M Home Linen Table Runner',
        slug: 'hm-home-linen-table-runner',
        brand: 'H&M Home',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Table Linens',
        finish: 'Natural Linen',
        images: [{ url: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-255-DEFAULT', price: 1200, compare_price: 1800, inventory_quantity: 100, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-256',
        name: 'Zara Home Cotton Tablecloth',
        slug: 'zara-home-cotton-tablecloth',
        brand: 'Zara Home',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Table Linens',
        finish: 'Cotton',
        images: [{ url: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-256-DEFAULT', price: 2500, compare_price: 3200, inventory_quantity: 80, inventory_reserved: 0 }],
    },
    // Coasters
    {
        _id: 'VG-257',
        name: 'Nestasia Marble Coaster Set',
        slug: 'nestasia-marble-coaster-set',
        brand: 'Nestasia',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Coasters',
        finish: 'Marble',
        images: [{ url: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-257-DEFAULT', price: 1800, compare_price: 2400, inventory_quantity: 120, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-258',
        name: 'Ellementry Cork Coaster Set of 6',
        slug: 'ellementry-cork-coaster-set',
        brand: 'Ellementry',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Coasters',
        finish: 'Cork',
        images: [{ url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-258-DEFAULT', price: 950, compare_price: 1400, inventory_quantity: 150, inventory_reserved: 0 }],
    },
    // Dining Serveware
    {
        _id: 'VG-259',
        name: 'Ellementry Ceramic Serving Bowl',
        slug: 'ellementry-ceramic-serving-bowl',
        brand: 'Ellementry',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Dining Serveware',
        finish: 'Ceramic',
        images: [{ url: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-259-DEFAULT', price: 2200, compare_price: 3000, inventory_quantity: 90, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-260',
        name: 'Nestasia Wooden Serving Tray',
        slug: 'nestasia-wooden-serving-tray',
        brand: 'Nestasia',
        category: 'Dining',
        subcategory: 'Dining Decor',
        item_type: 'Dining Serveware',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-260-DEFAULT', price: 1600, compare_price: 2200, inventory_quantity: 110, inventory_reserved: 0 }],
    },

    // ─── STUDY > STUDY TABLES ──────────────────────────────
    {
        _id: 'VG-117',
        name: 'Godrej Interio Study Table',
        slug: 'godrej-interio-study-table',
        brand: 'Godrej Interio',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Solid Wood Tables',
        finish: 'Engineered Wood & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-117-DEFAULT', price: 13500, compare_price: 15000, inventory_quantity: 22, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-261',
        name: 'Wooden Street Solid Sheesham Study Table',
        slug: 'wooden-street-solid-sheesham-study-table',
        brand: 'Wooden Street',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Solid Wood Tables',
        finish: 'Sheesham Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-261-DEFAULT', price: 22000, compare_price: 28000, inventory_quantity: 16, inventory_reserved: 0 }],
    },
    // Computer Tables
    {
        _id: 'VG-262',
        name: 'IKEA Micke Computer Desk',
        slug: 'ikea-micke-computer-desk',
        brand: 'IKEA',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Computer Tables',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-262-DEFAULT', price: 8500, compare_price: 11000, inventory_quantity: 40, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-263',
        name: 'Spacewood L-Shape Computer Table',
        slug: 'spacewood-l-shape-computer-table',
        brand: 'Spacewood',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Computer Tables',
        finish: 'Engineered Wood & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-263-DEFAULT', price: 18000, compare_price: 24000, inventory_quantity: 20, inventory_reserved: 0 }],
    },
    // Foldable Tables
    {
        _id: 'VG-264',
        name: 'Nilkamal Foldable Study Table',
        slug: 'nilkamal-foldable-study-table',
        brand: 'Nilkamal',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Foldable Tables',
        finish: 'Plastic & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-264-DEFAULT', price: 3500, compare_price: 5000, inventory_quantity: 65, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-265',
        name: 'IKEA Norberg Foldable Wall Table',
        slug: 'ikea-norberg-foldable-wall-table',
        brand: 'IKEA',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Foldable Tables',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-265-DEFAULT', price: 5500, compare_price: 7000, inventory_quantity: 50, inventory_reserved: 0 }],
    },
    // Corner Desks
    {
        _id: 'VG-154',
        name: 'Urban Ladder Premium Corner Desk',
        slug: 'urban-ladder-premium-corner-desk',
        brand: 'Urban Ladder',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Corner Desks',
        finish: 'Solid Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-154-DEFAULT', price: 41277, compare_price: 43450, inventory_quantity: 3, inventory_reserved: 0 }],
    },
    // Writing Desks
    {
        _id: 'VG-156',
        name: 'Spacewood Executive Writing Desk',
        slug: 'spacewood-executive-writing-desk',
        brand: 'Spacewood',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Writing Desks',
        finish: 'Solid Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1495514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-156-DEFAULT', price: 51320, compare_price: 60377, inventory_quantity: 4, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-266',
        name: 'Wooden Street Teak Writing Desk',
        slug: 'wooden-street-teak-writing-desk',
        brand: 'Wooden Street',
        category: 'Study',
        subcategory: 'Study Tables',
        item_type: 'Writing Desks',
        finish: 'Teak Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-266-DEFAULT', price: 28000, compare_price: 36000, inventory_quantity: 10, inventory_reserved: 0 }],
    },

    // ─── STUDY > OFFICE CHAIRS ─────────────────────────────
    {
        _id: 'VG-107',
        name: 'Herman Miller Aeron Chair',
        slug: 'herman-miller-aeron-chair',
        brand: 'Herman Miller',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Ergonomic Chairs',
        finish: 'Breathable Mesh & Aluminum',
        images: [{ url: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-107-DEFAULT', price: 109250, compare_price: 115000, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-150',
        name: 'CellBell Comfort Kneeling Chair',
        slug: 'cellbell-comfort-kneeling-chair',
        brand: 'CellBell',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Ergonomic Chairs',
        finish: 'Breathable Mesh & Aluminum',
        images: [{ url: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-150-DEFAULT', price: 51327, compare_price: 73325, inventory_quantity: 63, inventory_reserved: 0 }],
    },
    // Executive Chairs
    {
        _id: 'VG-149',
        name: 'Spacewood Leather Conference Chair',
        slug: 'spacewood-leather-conference-chair',
        brand: 'Spacewood',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Executive Chairs',
        finish: 'Leather & Chrome',
        images: [{ url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-149-DEFAULT', price: 113476, compare_price: 119449, inventory_quantity: 94, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-267',
        name: 'Godrej Interio Executive High-Back Chair',
        slug: 'godrej-interio-executive-high-back-chair',
        brand: 'Godrej Interio',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Executive Chairs',
        finish: 'PU Leather & Chrome',
        images: [{ url: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-267-DEFAULT', price: 28000, compare_price: 36000, inventory_quantity: 30, inventory_reserved: 0 }],
    },
    // Study Chairs
    {
        _id: 'VG-268',
        name: 'IKEA Vilmar Study Chair',
        slug: 'ikea-vilmar-study-chair',
        brand: 'IKEA',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Study Chairs',
        finish: 'Chrome & Fabric',
        images: [{ url: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-268-DEFAULT', price: 6500, compare_price: 8500, inventory_quantity: 55, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-269',
        name: 'Nilkamal Mesh Study Chair',
        slug: 'nilkamal-mesh-study-chair',
        brand: 'Nilkamal',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Study Chairs',
        finish: 'Mesh & Plastic',
        images: [{ url: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-269-DEFAULT', price: 4800, compare_price: 6500, inventory_quantity: 70, inventory_reserved: 0 }],
    },
    // Gaming Chairs
    {
        _id: 'VG-148',
        name: 'Nilkamal Comfort Gaming Chair',
        slug: 'nilkamal-comfort-gaming-chair',
        brand: 'Nilkamal',
        category: 'Study',
        subcategory: 'Office Chairs',
        item_type: 'Gaming Chairs',
        finish: 'Memory Foam & Mesh',
        images: [{ url: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-148-DEFAULT', price: 107127, compare_price: 112766, inventory_quantity: 88, inventory_reserved: 0 }],
    },

    // ─── STUDY > OFFICE STORAGE ────────────────────────────
    // File Cabinets
    {
        _id: 'VG-270',
        name: 'Godrej Interio Metal File Cabinet',
        slug: 'godrej-interio-metal-file-cabinet',
        brand: 'Godrej Interio',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'File Cabinets',
        finish: 'Powder Coated Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-270-DEFAULT', price: 12000, compare_price: 16000, inventory_quantity: 30, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-271',
        name: 'Spacewood Wooden File Cabinet',
        slug: 'spacewood-wooden-file-cabinet',
        brand: 'Spacewood',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'File Cabinets',
        finish: 'Engineered Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-271-DEFAULT', price: 18000, compare_price: 24000, inventory_quantity: 20, inventory_reserved: 0 }],
    },
    // Office Bookcases
    {
        _id: 'VG-110b',
        name: 'Urban Ladder Ladder Bookshelf',
        slug: 'urban-ladder-ladder-bookshelf',
        brand: 'Urban Ladder',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'Office Bookcases',
        finish: 'Metal & Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-110b-DEFAULT', price: 22000, compare_price: 28000, inventory_quantity: 18, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-272',
        name: 'IKEA Kallax Office Bookcase',
        slug: 'ikea-kallax-office-bookcase',
        brand: 'IKEA',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'Office Bookcases',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-272-DEFAULT', price: 9500, compare_price: 12000, inventory_quantity: 45, inventory_reserved: 0 }],
    },
    // Wall Shelves
    {
        _id: 'VG-273',
        name: 'Wooden Street Floating Wall Shelves',
        slug: 'wooden-street-floating-wall-shelves',
        brand: 'Wooden Street',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'Wall Shelves',
        finish: 'Mango Wood',
        images: [{ url: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-273-DEFAULT', price: 5500, compare_price: 7000, inventory_quantity: 60, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-274',
        name: 'IKEA Lack Wall Shelf',
        slug: 'ikea-lack-wall-shelf',
        brand: 'IKEA',
        category: 'Study',
        subcategory: 'Office Storage',
        item_type: 'Wall Shelves',
        finish: 'White Laminate',
        images: [{ url: 'https://images.unsplash.com/photo-1595514535415-38d1796dcf98?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-274-DEFAULT', price: 2500, compare_price: 3500, inventory_quantity: 90, inventory_reserved: 0 }],
    },

    // ─── DECOR ─────────────────────────────────────────────
    {
        _id: 'VG-116',
        name: 'CB2 Modern Wall Mirror',
        slug: 'cb2-modern-wall-mirror',
        brand: 'CB2',
        category: 'Decor',
        subcategory: 'Mirrors',
        item_type: 'Wall Mirrors',
        finish: 'Glass & Metal Frame',
        images: [{ url: 'https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-116-DEFAULT', price: 18000, compare_price: 18000, inventory_quantity: 4, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-157',
        name: 'Home Centre Statement LED Mirror',
        slug: 'home-centre-statement-led-mirror',
        brand: 'Home Centre',
        category: 'Decor',
        subcategory: 'Mirrors',
        item_type: 'LED Mirrors',
        finish: 'Glass & Metal Frame',
        images: [{ url: 'https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-157-DEFAULT', price: 33768, compare_price: 39728, inventory_quantity: 1, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-158',
        name: 'Urban Ladder Elegant Floor Mirror',
        slug: 'urban-ladder-elegant-floor-mirror',
        brand: 'Urban Ladder',
        category: 'Decor',
        subcategory: 'Mirrors',
        item_type: 'Floor Mirrors',
        finish: 'Bamboo Frame',
        images: [{ url: 'https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-158-DEFAULT', price: 23568, compare_price: 29460, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-159',
        name: 'Nestasia Decorative Vanity Mirror',
        slug: 'nestasia-decorative-vanity-mirror',
        brand: 'Nestasia',
        category: 'Decor',
        subcategory: 'Mirrors',
        item_type: 'Vanity Mirrors',
        finish: 'Acrylic Frame',
        images: [{ url: 'https://images.unsplash.com/photo-1618220179428-22790b46a0eb?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-159-DEFAULT', price: 14742, compare_price: 16380, inventory_quantity: 4, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-118',
        name: 'H&M Home Ceramic Planter',
        slug: 'hm-home-ceramic-planter',
        brand: 'H&M Home',
        category: 'Decor',
        subcategory: 'Planters',
        item_type: 'Planters',
        finish: 'Ceramic',
        images: [{ url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-118-DEFAULT', price: 3325, compare_price: 3500, inventory_quantity: 60, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-160',
        name: 'Ellementry Artisan Wall Planter',
        slug: 'ellementry-artisan-wall-planter',
        brand: 'Ellementry',
        category: 'Decor',
        subcategory: 'Planters',
        item_type: 'Wall Planters',
        finish: 'Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-160-DEFAULT', price: 12384, compare_price: 14570, inventory_quantity: 84, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-161',
        name: 'Pepperfry Ceramic Planter',
        slug: 'pepperfry-ceramic-planter',
        brand: 'Pepperfry',
        category: 'Decor',
        subcategory: 'Planters',
        item_type: 'Ceramic Planters',
        finish: 'Plastic',
        images: [{ url: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-161-DEFAULT', price: 8397, compare_price: 10497, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-119',
        name: 'Zara Home Table Lamp',
        slug: 'zara-home-table-lamp',
        brand: 'Zara Home',
        category: 'Decor',
        subcategory: 'Lamps',
        item_type: 'Table Lamps',
        finish: 'Ceramic & Linen Shade',
        images: [{ url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-119-DEFAULT', price: 7225, compare_price: 8500, inventory_quantity: 35, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-163',
        name: 'Urban Ladder Ambient Floor Lamp',
        slug: 'urban-ladder-ambient-floor-lamp',
        brand: 'Urban Ladder',
        category: 'Decor',
        subcategory: 'Lamps',
        item_type: 'Floor Lamps',
        finish: 'Marble & Metal',
        images: [{ url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-163-DEFAULT', price: 10989, compare_price: 12210, inventory_quantity: 3, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-164',
        name: 'Home Centre Designer Desk Lamp',
        slug: 'home-centre-designer-desk-lamp',
        brand: 'Home Centre',
        category: 'Decor',
        subcategory: 'Lamps',
        item_type: 'Desk Lamps',
        finish: 'Metal & Fabric Shade',
        images: [{ url: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-164-DEFAULT', price: 16911, compare_price: 16911, inventory_quantity: 0, inventory_reserved: 0 }],
    },
    {
        _id: 'VG-165',
        name: 'Pepperfry Rattan Wall Sconce',
        slug: 'pepperfry-rattan-wall-sconce',
        brand: 'Pepperfry',
        category: 'Decor',
        subcategory: 'Lamps',
        item_type: 'Wall Sconces',
        finish: 'Rattan & Cotton',
        images: [{ url: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=400&q=80', is_primary: true }],
        variants: [{ variant_id: 'VG-165-DEFAULT', price: 6635, compare_price: 8847, inventory_quantity: 88, inventory_reserved: 0 }],
    },
];

export const MOCK_PRODUCTS = mockProducts;
export default mockProducts;